module ExpectedVars
  module Season
    SEASON_RACE_LIST_1950 = [{"season"=>"1950",
  "round"=>"1",
  "url"=>"http://en.wikipedia.org/wiki/1950_British_Grand_Prix",
  "raceName"=>"British Grand Prix",
  "Circuit"=>
   {"circuitId"=>"silverstone",
    "url"=>"http://en.wikipedia.org/wiki/Silverstone_Circuit",
    "circuitName"=>"Silverstone Circuit",
    "Location"=>{"lat"=>"52.0786", "long"=>"-1.01694", "locality"=>"Silverstone", "country"=>"UK"}},
  "date"=>"1950-05-13"},
 {"season"=>"1950",
  "round"=>"2",
  "url"=>"http://en.wikipedia.org/wiki/1950_Monaco_Grand_Prix",
  "raceName"=>"Monaco Grand Prix",
  "Circuit"=>
   {"circuitId"=>"monaco",
    "url"=>"http://en.wikipedia.org/wiki/Circuit_de_Monaco",
    "circuitName"=>"Circuit de Monaco",
    "Location"=>{"lat"=>"43.7347", "long"=>"7.42056", "locality"=>"Monte-Carlo", "country"=>"Monaco"}},
  "date"=>"1950-05-21"},
 {"season"=>"1950",
  "round"=>"3",
  "url"=>"http://en.wikipedia.org/wiki/1950_Indianapolis_500",
  "raceName"=>"Indianapolis 500",
  "Circuit"=>
   {"circuitId"=>"indianapolis",
    "url"=>"http://en.wikipedia.org/wiki/Indianapolis_Motor_Speedway",
    "circuitName"=>"Indianapolis Motor Speedway",
    "Location"=>{"lat"=>"39.795", "long"=>"-86.2347", "locality"=>"Indianapolis", "country"=>"USA"}},
  "date"=>"1950-05-30"},
 {"season"=>"1950",
  "round"=>"4",
  "url"=>"http://en.wikipedia.org/wiki/1950_Swiss_Grand_Prix",
  "raceName"=>"Swiss Grand Prix",
  "Circuit"=>
   {"circuitId"=>"bremgarten",
    "url"=>"http://en.wikipedia.org/wiki/Circuit_Bremgarten",
    "circuitName"=>"Circuit Bremgarten",
    "Location"=>{"lat"=>"46.9589", "long"=>"7.40194", "locality"=>"Bern", "country"=>"Switzerland"}},
  "date"=>"1950-06-04"},
 {"season"=>"1950",
  "round"=>"5",
  "url"=>"http://en.wikipedia.org/wiki/1950_Belgian_Grand_Prix",
  "raceName"=>"Belgian Grand Prix",
  "Circuit"=>
   {"circuitId"=>"spa",
    "url"=>"http://en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps",
    "circuitName"=>"Circuit de Spa-Francorchamps",
    "Location"=>{"lat"=>"50.4372", "long"=>"5.97139", "locality"=>"Spa", "country"=>"Belgium"}},
  "date"=>"1950-06-18"},
 {"season"=>"1950",
  "round"=>"6",
  "url"=>"http://en.wikipedia.org/wiki/1950_French_Grand_Prix",
  "raceName"=>"French Grand Prix",
  "Circuit"=>
   {"circuitId"=>"reims",
    "url"=>"http://en.wikipedia.org/wiki/Reims-Gueux",
    "circuitName"=>"Reims-Gueux",
    "Location"=>{"lat"=>"49.2542", "long"=>"3.93083", "locality"=>"Reims", "country"=>"France"}},
  "date"=>"1950-07-02"},
 {"season"=>"1950",
  "round"=>"7",
  "url"=>"http://en.wikipedia.org/wiki/1950_Italian_Grand_Prix",
  "raceName"=>"Italian Grand Prix",
  "Circuit"=>
   {"circuitId"=>"monza",
    "url"=>"http://en.wikipedia.org/wiki/Autodromo_Nazionale_Monza",
    "circuitName"=>"Autodromo Nazionale di Monza",
    "Location"=>{"lat"=>"45.6156", "long"=>"9.28111", "locality"=>"Monza", "country"=>"Italy"}},
  "date"=>"1950-09-03"}]
  
    MONZA_1950_RACE = {"season"=>"1950",
    "round"=>"7",
    "url"=>"http://en.wikipedia.org/wiki/1950_Italian_Grand_Prix",
    "raceName"=>"Italian Grand Prix",
    "Circuit"=>
     {"circuitId"=>"monza",
      "url"=>"http://en.wikipedia.org/wiki/Autodromo_Nazionale_Monza",
      "circuitName"=>"Autodromo Nazionale di Monza",
      "Location"=>{"lat"=>"45.6156", "long"=>"9.28111", "locality"=>"Monza", "country"=>"Italy"}},
    "date"=>"1950-09-03"}

    CURRENT_SEASON = [{"season"=>"2017",
    "round"=>"1",
    "url"=>"https://en.wikipedia.org/wiki/2017_Australian_Grand_Prix",
    "raceName"=>"Australian Grand Prix",
    "Circuit"=>
     {"circuitId"=>"albert_park",
      "url"=>"http://en.wikipedia.org/wiki/Melbourne_Grand_Prix_Circuit",
      "circuitName"=>"Albert Park Grand Prix Circuit",
      "Location"=>{"lat"=>"-37.8497", "long"=>"144.968", "locality"=>"Melbourne", "country"=>"Australia"}},
    "date"=>"2017-03-26",
    "time"=>"05:00:00Z"},
   {"season"=>"2017",
    "round"=>"2",
    "url"=>"https://en.wikipedia.org/wiki/2017_Chinese_Grand_Prix",
    "raceName"=>"Chinese Grand Prix",
    "Circuit"=>
     {"circuitId"=>"shanghai",
      "url"=>"http://en.wikipedia.org/wiki/Shanghai_International_Circuit",
      "circuitName"=>"Shanghai International Circuit",
      "Location"=>{"lat"=>"31.3389", "long"=>"121.22", "locality"=>"Shanghai", "country"=>"China"}},
    "date"=>"2017-04-09",
    "time"=>"06:00:00Z"},
   {"season"=>"2017",
    "round"=>"3",
    "url"=>"https://en.wikipedia.org/wiki/2017_Bahrain_Grand_Prix",
    "raceName"=>"Bahrain Grand Prix",
    "Circuit"=>
     {"circuitId"=>"bahrain",
      "url"=>"http://en.wikipedia.org/wiki/Bahrain_International_Circuit",
      "circuitName"=>"Bahrain International Circuit",
      "Location"=>{"lat"=>"26.0325", "long"=>"50.5106", "locality"=>"Sakhir", "country"=>"Bahrain"}},
    "date"=>"2017-04-16",
    "time"=>"15:00:00Z"},
   {"season"=>"2017",
    "round"=>"4",
    "url"=>"https://en.wikipedia.org/wiki/2017_Russian_Grand_Prix",
    "raceName"=>"Russian Grand Prix",
    "Circuit"=>
     {"circuitId"=>"sochi",
      "url"=>"http://en.wikipedia.org/wiki/Sochi_Autodrom",
      "circuitName"=>"Sochi Autodrom",
      "Location"=>{"lat"=>"43.4057", "long"=>"39.9578", "locality"=>"Sochi", "country"=>"Russia"}},
    "date"=>"2017-04-30",
    "time"=>"12:00:00Z"},
   {"season"=>"2017",
    "round"=>"5",
    "url"=>"https://en.wikipedia.org/wiki/2017_Spanish_Grand_Prix",
    "raceName"=>"Spanish Grand Prix",
    "Circuit"=>
     {"circuitId"=>"catalunya",
      "url"=>"http://en.wikipedia.org/wiki/Circuit_de_Barcelona-Catalunya",
      "circuitName"=>"Circuit de Barcelona-Catalunya",
      "Location"=>{"lat"=>"41.57", "long"=>"2.26111", "locality"=>"Montmeló", "country"=>"Spain"}},
    "date"=>"2017-05-14",
    "time"=>"12:00:00Z"},
   {"season"=>"2017",
    "round"=>"6",
    "url"=>"https://en.wikipedia.org/wiki/2017_Monaco_Grand_Prix",
    "raceName"=>"Monaco Grand Prix",
    "Circuit"=>
     {"circuitId"=>"monaco",
      "url"=>"http://en.wikipedia.org/wiki/Circuit_de_Monaco",
      "circuitName"=>"Circuit de Monaco",
      "Location"=>{"lat"=>"43.7347", "long"=>"7.42056", "locality"=>"Monte-Carlo", "country"=>"Monaco"}},
    "date"=>"2017-05-28",
    "time"=>"12:00:00Z"},
   {"season"=>"2017",
    "round"=>"7",
    "url"=>"https://en.wikipedia.org/wiki/2017_Canadian_Grand_Prix",
    "raceName"=>"Canadian Grand Prix",
    "Circuit"=>
     {"circuitId"=>"villeneuve",
      "url"=>"http://en.wikipedia.org/wiki/Circuit_Gilles_Villeneuve",
      "circuitName"=>"Circuit Gilles Villeneuve",
      "Location"=>{"lat"=>"45.5", "long"=>"-73.5228", "locality"=>"Montreal", "country"=>"Canada"}},
    "date"=>"2017-06-11",
    "time"=>"18:00:00Z"},
   {"season"=>"2017",
    "round"=>"8",
    "url"=>"https://en.wikipedia.org/wiki/2017_Azerbaijan_Grand_Prix",
    "raceName"=>"Azerbaijan Grand Prix",
    "Circuit"=>
     {"circuitId"=>"BAK",
      "url"=>"http://en.wikipedia.org/wiki/Baku_City_Circuit",
      "circuitName"=>"Baku City Circuit",
      "Location"=>{"lat"=>"40.3725", "long"=>"49.8533", "locality"=>"Baku", "country"=>"Azerbaijan"}},
    "date"=>"2017-06-25",
    "time"=>"13:00:00Z"},
   {"season"=>"2017",
    "round"=>"9",
    "url"=>"https://en.wikipedia.org/wiki/2017_Austrian_Grand_Prix",
    "raceName"=>"Austrian Grand Prix",
    "Circuit"=>
     {"circuitId"=>"red_bull_ring",
      "url"=>"http://en.wikipedia.org/wiki/Red_Bull_Ring",
      "circuitName"=>"Red Bull Ring",
      "Location"=>{"lat"=>"47.2197", "long"=>"14.7647", "locality"=>"Spielburg", "country"=>"Austria"}},
    "date"=>"2017-07-09",
    "time"=>"12:00:00Z"},
   {"season"=>"2017",
    "round"=>"10",
    "url"=>"https://en.wikipedia.org/wiki/2017_British_Grand_Prix",
    "raceName"=>"British Grand Prix",
    "Circuit"=>
     {"circuitId"=>"silverstone",
      "url"=>"http://en.wikipedia.org/wiki/Silverstone_Circuit",
      "circuitName"=>"Silverstone Circuit",
      "Location"=>{"lat"=>"52.0786", "long"=>"-1.01694", "locality"=>"Silverstone", "country"=>"UK"}},
    "date"=>"2017-07-16",
    "time"=>"12:00:00Z"},
   {"season"=>"2017",
    "round"=>"11",
    "url"=>"https://en.wikipedia.org/wiki/2017_Hungarian_Grand_Prix",
    "raceName"=>"Hungarian Grand Prix",
    "Circuit"=>
     {"circuitId"=>"hungaroring",
      "url"=>"http://en.wikipedia.org/wiki/Hungaroring",
      "circuitName"=>"Hungaroring",
      "Location"=>{"lat"=>"47.5789", "long"=>"19.2486", "locality"=>"Budapest", "country"=>"Hungary"}},
    "date"=>"2017-07-30",
    "time"=>"12:00:00Z"},
   {"season"=>"2017",
    "round"=>"12",
    "url"=>"https://en.wikipedia.org/wiki/2017_Belgian_Grand_Prix",
    "raceName"=>"Belgian Grand Prix",
    "Circuit"=>
     {"circuitId"=>"spa",
      "url"=>"http://en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps",
      "circuitName"=>"Circuit de Spa-Francorchamps",
      "Location"=>{"lat"=>"50.4372", "long"=>"5.97139", "locality"=>"Spa", "country"=>"Belgium"}},
    "date"=>"2017-08-27",
    "time"=>"12:00:00Z"},
   {"season"=>"2017",
    "round"=>"13",
    "url"=>"https://en.wikipedia.org/wiki/2017_Italian_Grand_Prix",
    "raceName"=>"Italian Grand Prix",
    "Circuit"=>
     {"circuitId"=>"monza",
      "url"=>"http://en.wikipedia.org/wiki/Autodromo_Nazionale_Monza",
      "circuitName"=>"Autodromo Nazionale di Monza",
      "Location"=>{"lat"=>"45.6156", "long"=>"9.28111", "locality"=>"Monza", "country"=>"Italy"}},
    "date"=>"2017-09-03",
    "time"=>"12:00:00Z"},
   {"season"=>"2017",
    "round"=>"14",
    "url"=>"https://en.wikipedia.org/wiki/2017_Singapore_Grand_Prix",
    "raceName"=>"Singapore Grand Prix",
    "Circuit"=>
     {"circuitId"=>"marina_bay",
      "url"=>"http://en.wikipedia.org/wiki/Marina_Bay_Street_Circuit",
      "circuitName"=>"Marina Bay Street Circuit",
      "Location"=>{"lat"=>"1.2914", "long"=>"103.864", "locality"=>"Marina Bay", "country"=>"Singapore"}},
    "date"=>"2017-09-17",
    "time"=>"12:00:00Z"},
   {"season"=>"2017",
    "round"=>"15",
    "url"=>"https://en.wikipedia.org/wiki/2017_Malaysian_Grand_Prix",
    "raceName"=>"Malaysian Grand Prix",
    "Circuit"=>
     {"circuitId"=>"sepang",
      "url"=>"http://en.wikipedia.org/wiki/Sepang_International_Circuit",
      "circuitName"=>"Sepang International Circuit",
      "Location"=>{"lat"=>"2.76083", "long"=>"101.738", "locality"=>"Kuala Lumpur", "country"=>"Malaysia"}},
    "date"=>"2017-10-01",
    "time"=>"07:00:00Z"},
   {"season"=>"2017",
    "round"=>"16",
    "url"=>"https://en.wikipedia.org/wiki/2017_Japanese_Grand_Prix",
    "raceName"=>"Japanese Grand Prix",
    "Circuit"=>
     {"circuitId"=>"suzuka",
      "url"=>"http://en.wikipedia.org/wiki/Suzuka_Circuit",
      "circuitName"=>"Suzuka Circuit",
      "Location"=>{"lat"=>"34.8431", "long"=>"136.541", "locality"=>"Suzuka", "country"=>"Japan"}},
    "date"=>"2017-10-08",
    "time"=>"05:00:00Z"},
   {"season"=>"2017",
    "round"=>"17",
    "url"=>"https://en.wikipedia.org/wiki/2017_United_States_Grand_Prix",
    "raceName"=>"United States Grand Prix",
    "Circuit"=>
     {"circuitId"=>"americas",
      "url"=>"http://en.wikipedia.org/wiki/Circuit_of_the_Americas",
      "circuitName"=>"Circuit of the Americas",
      "Location"=>{"lat"=>"30.1328", "long"=>"-97.6411", "locality"=>"Austin", "country"=>"USA"}},
    "date"=>"2017-10-22",
    "time"=>"19:00:00Z"},
   {"season"=>"2017",
    "round"=>"18",
    "url"=>"https://en.wikipedia.org/wiki/2017_Mexican_Grand_Prix",
    "raceName"=>"Mexican Grand Prix",
    "Circuit"=>
     {"circuitId"=>"rodriguez",
      "url"=>"http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez",
      "circuitName"=>"Autódromo Hermanos Rodríguez",
      "Location"=>{"lat"=>"19.4042", "long"=>"-99.0907", "locality"=>"Mexico City", "country"=>"Mexico"}},
    "date"=>"2017-10-29",
    "time"=>"19:00:00Z"},
   {"season"=>"2017",
    "round"=>"19",
    "url"=>"https://en.wikipedia.org/wiki/2017_Brazilian_Grand_Prix",
    "raceName"=>"Brazilian Grand Prix",
    "Circuit"=>
     {"circuitId"=>"interlagos",
      "url"=>"http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jos%C3%A9_Carlos_Pace",
      "circuitName"=>"Autódromo José Carlos Pace",
      "Location"=>{"lat"=>"-23.7036", "long"=>"-46.6997", "locality"=>"São Paulo", "country"=>"Brazil"}},
    "date"=>"2017-11-12",
    "time"=>"16:00:00Z"},
   {"season"=>"2017",
    "round"=>"20",
    "url"=>"https://en.wikipedia.org/wiki/2017_Abu_Dhabi_Grand_Prix",
    "raceName"=>"Abu Dhabi Grand Prix",
    "Circuit"=>
     {"circuitId"=>"yas_marina",
      "url"=>"http://en.wikipedia.org/wiki/Yas_Marina_Circuit",
      "circuitName"=>"Yas Marina Circuit",
      "Location"=>{"lat"=>"24.4672", "long"=>"54.6031", "locality"=>"Abu Dhabi", "country"=>"UAE"}},
    "date"=>"2017-11-26",
    "time"=>"17:00:00Z"}]

    DRIVER_STANDINGS_1950 = [{"position"=>"1", "positionText"=>"1", "points"=>"30", "wins"=>"3", "Driver"=>{"driverId"=>"farina", "url"=>"http://en.wikipedia.org/wiki/Nino_Farina", "givenName"=>"Nino", "familyName"=>"Farina", "dateOfBirth"=>"1906-10-30", "nationality"=>"Italian"}, "Constructors"=>[{"constructorId"=>"alfa", "url"=>"http://en.wikipedia.org/wiki/Alfa_Romeo_(Formula_One)", "name"=>"Alfa Romeo", "nationality"=>"Italian"}]}, {"position"=>"2", "positionText"=>"2", "points"=>"27", "wins"=>"3", "Driver"=>{"driverId"=>"fangio", "url"=>"http://en.wikipedia.org/wiki/Juan_Manuel_Fangio", "givenName"=>"Juan", "familyName"=>"Fangio", "dateOfBirth"=>"1911-06-24", "nationality"=>"Argentine"}, "Constructors"=>[{"constructorId"=>"alfa", "url"=>"http://en.wikipedia.org/wiki/Alfa_Romeo_(Formula_One)", "name"=>"Alfa Romeo", "nationality"=>"Italian"}]}, {"position"=>"3", "positionText"=>"3", "points"=>"24", "wins"=>"0", "Driver"=>{"driverId"=>"fagioli", "url"=>"http://en.wikipedia.org/wiki/Luigi_Fagioli", "givenName"=>"Luigi", "familyName"=>"Fagioli", "dateOfBirth"=>"1898-06-09", "nationality"=>"Italian"}, "Constructors"=>[{"constructorId"=>"alfa", "url"=>"http://en.wikipedia.org/wiki/Alfa_Romeo_(Formula_One)", "name"=>"Alfa Romeo", "nationality"=>"Italian"}]}, {"position"=>"4", "positionText"=>"4", "points"=>"13", "wins"=>"0", "Driver"=>{"driverId"=>"rosier", "url"=>"http://en.wikipedia.org/wiki/Louis_Rosier", "givenName"=>"Louis", "familyName"=>"Rosier", "dateOfBirth"=>"1905-11-05", "nationality"=>"French"}, "Constructors"=>[{"constructorId"=>"lago", "url"=>"http://en.wikipedia.org/wiki/Talbot-Lago", "name"=>"Talbot-Lago", "nationality"=>"French"}]}, {"position"=>"5", "positionText"=>"5", "points"=>"11", "wins"=>"0", "Driver"=>{"driverId"=>"ascari", "url"=>"http://en.wikipedia.org/wiki/Alberto_Ascari", "givenName"=>"Alberto", "familyName"=>"Ascari", "dateOfBirth"=>"1918-07-13", "nationality"=>"Italian"}, "Constructors"=>[{"constructorId"=>"ferrari", "url"=>"http://en.wikipedia.org/wiki/Scuderia_Ferrari", "name"=>"Ferrari", "nationality"=>"Italian"}, {"constructorId"=>"alfa", "url"=>"http://en.wikipedia.org/wiki/Alfa_Romeo_(Formula_One)", "name"=>"Alfa Romeo", "nationality"=>"Italian"}]}, {"position"=>"6", "positionText"=>"6", "points"=>"9", "wins"=>"1", "Driver"=>{"driverId"=>"parsons", "url"=>"http://en.wikipedia.org/wiki/Johnnie_Parsons", "givenName"=>"Johnnie", "familyName"=>"Parsons", "dateOfBirth"=>"1918-07-04", "nationality"=>"American"}, "Constructors"=>[{"constructorId"=>"kurtis_kraft", "url"=>"http://en.wikipedia.org/wiki/Kurtis_Kraft", "name"=>"Kurtis Kraft", "nationality"=>"American"}]}, {"position"=>"7", "positionText"=>"7", "points"=>"6", "wins"=>"0", "Driver"=>{"driverId"=>"holland", "url"=>"http://en.wikipedia.org/wiki/Bill_Holland", "givenName"=>"Bill", "familyName"=>"Holland", "dateOfBirth"=>"1907-12-18", "nationality"=>"American"}, "Constructors"=>[{"constructorId"=>"deidt", "url"=>"http://en.wikipedia.org/wiki/Deidt", "name"=>"Deidt", "nationality"=>"American"}]}, {"position"=>"8", "positionText"=>"8", "points"=>"5", "wins"=>"0", "Driver"=>{"driverId"=>"bira", "url"=>"http://en.wikipedia.org/wiki/Prince_Bira", "givenName"=>"Prince", "familyName"=>"Bira", "dateOfBirth"=>"1914-07-15", "nationality"=>"Thai"}, "Constructors"=>[{"constructorId"=>"maserati", "url"=>"http://en.wikipedia.org/wiki/Maserati", "name"=>"Maserati", "nationality"=>"Italian"}]}, {"position"=>"9", "positionText"=>"9", "points"=>"4", "wins"=>"0", "Driver"=>{"driverId"=>"whitehead", "url"=>"http://en.wikipedia.org/wiki/Peter_Whitehead_(racing_driver)", "givenName"=>"Peter", "familyName"=>"Whitehead", "dateOfBirth"=>"1914-11-12", "nationality"=>"British"}, "Constructors"=>[{"constructorId"=>"ferrari", "url"=>"http://en.wikipedia.org/wiki/Scuderia_Ferrari", "name"=>"Ferrari", "nationality"=>"Italian"}]}, {"position"=>"10", "positionText"=>"10", "points"=>"4", "wins"=>"0", "Driver"=>{"driverId"=>"chiron", "url"=>"http://en.wikipedia.org/wiki/Louis_Chiron", "givenName"=>"Louis", "familyName"=>"Chiron", "dateOfBirth"=>"1899-08-03", "nationality"=>"Monegasque"}, "Constructors"=>[{"constructorId"=>"maserati", "url"=>"http://en.wikipedia.org/wiki/Maserati", "name"=>"Maserati", "nationality"=>"Italian"}]}, {"position"=>"11", "positionText"=>"11", "points"=>"4", "wins"=>"0", "Driver"=>{"driverId"=>"reg_parnell", "url"=>"http://en.wikipedia.org/wiki/Reg_Parnell", "givenName"=>"Reg", "familyName"=>"Parnell", "dateOfBirth"=>"1911-07-02", "nationality"=>"British"}, "Constructors"=>[{"constructorId"=>"alfa", "url"=>"http://en.wikipedia.org/wiki/Alfa_Romeo_(Formula_One)", "name"=>"Alfa Romeo", "nationality"=>"Italian"}, {"constructorId"=>"maserati", "url"=>"http://en.wikipedia.org/wiki/Maserati", "name"=>"Maserati", "nationality"=>"Italian"}]}, {"position"=>"12", "positionText"=>"12", "points"=>"4", "wins"=>"0", "Driver"=>{"driverId"=>"rose", "url"=>"http://en.wikipedia.org/wiki/Mauri_Rose", "givenName"=>"Mauri", "familyName"=>"Rose", "dateOfBirth"=>"1906-05-26", "nationality"=>"American"}, "Constructors"=>[{"constructorId"=>"deidt", "url"=>"http://en.wikipedia.org/wiki/Deidt", "name"=>"Deidt", "nationality"=>"American"}]}, {"position"=>"13", "positionText"=>"13", "points"=>"3", "wins"=>"0", "Driver"=>{"driverId"=>"serafini", "url"=>"http://en.wikipedia.org/wiki/Dorino_Serafini", "givenName"=>"Dorino", "familyName"=>"Serafini", "dateOfBirth"=>"1909-07-22", "nationality"=>"Italian"}, "Constructors"=>[{"constructorId"=>"ferrari", "url"=>"http://en.wikipedia.org/wiki/Scuderia_Ferrari", "name"=>"Ferrari", "nationality"=>"Italian"}]}, {"position"=>"14", "positionText"=>"14", "points"=>"3", "wins"=>"0", "Driver"=>{"driverId"=>"cabantous", "url"=>"http://en.wikipedia.org/wiki/Yves_Giraud_Cabantous", "givenName"=>"Yves", "familyName"=>"Cabantous", "dateOfBirth"=>"1904-10-08", "nationality"=>"French"}, "Constructors"=>[{"constructorId"=>"lago", "url"=>"http://en.wikipedia.org/wiki/Talbot-Lago", "name"=>"Talbot-Lago", "nationality"=>"French"}]}, {"position"=>"15", "positionText"=>"15", "points"=>"3", "wins"=>"0", "Driver"=>{"driverId"=>"sommer", "url"=>"http://en.wikipedia.org/wiki/Raymond_Sommer", "givenName"=>"Raymond", "familyName"=>"Sommer", "dateOfBirth"=>"1906-08-31", "nationality"=>"French"}, "Constructors"=>[{"constructorId"=>"ferrari", "url"=>"http://en.wikipedia.org/wiki/Scuderia_Ferrari", "name"=>"Ferrari", "nationality"=>"Italian"}, {"constructorId"=>"lago", "url"=>"http://en.wikipedia.org/wiki/Talbot-Lago", "name"=>"Talbot-Lago", "nationality"=>"French"}]}, {"position"=>"16", "positionText"=>"16", "points"=>"3", "wins"=>"0", "Driver"=>{"driverId"=>"manzon", "url"=>"http://en.wikipedia.org/wiki/Robert_Manzon", "givenName"=>"Robert", "familyName"=>"Manzon", "dateOfBirth"=>"1917-04-12", "nationality"=>"French"}, "Constructors"=>[{"constructorId"=>"simca", "url"=>"http://en.wikipedia.org/wiki/Simca", "name"=>"Simca", "nationality"=>"French"}]}, {"position"=>"17", "positionText"=>"17", "points"=>"3", "wins"=>"0", "Driver"=>{"driverId"=>"green", "url"=>"http://en.wikipedia.org/wiki/Cecil_Green", "givenName"=>"Cecil", "familyName"=>"Green", "dateOfBirth"=>"1919-09-30", "nationality"=>"American"}, "Constructors"=>[{"constructorId"=>"kurtis_kraft", "url"=>"http://en.wikipedia.org/wiki/Kurtis_Kraft", "name"=>"Kurtis Kraft", "nationality"=>"American"}]}, {"position"=>"18", "positionText"=>"18", "points"=>"3", "wins"=>"0", "Driver"=>{"driverId"=>"etancelin", "url"=>"http://en.wikipedia.org/wiki/Philippe_%C3%89tancelin", "givenName"=>"Philippe", "familyName"=>"Étancelin", "dateOfBirth"=>"1896-12-28", "nationality"=>"French"}, "Constructors"=>[{"constructorId"=>"lago", "url"=>"http://en.wikipedia.org/wiki/Talbot-Lago", "name"=>"Talbot-Lago", "nationality"=>"French"}]}, {"position"=>"19", "positionText"=>"19", "points"=>"2", "wins"=>"0", "Driver"=>{"driverId"=>"bonetto", "url"=>"http://en.wikipedia.org/wiki/Felice_Bonetto", "givenName"=>"Felice", "familyName"=>"Bonetto", "dateOfBirth"=>"1903-06-09", "nationality"=>"Italian"}, "Constructors"=>[{"constructorId"=>"maserati", "url"=>"http://en.wikipedia.org/wiki/Maserati", "name"=>"Maserati", "nationality"=>"Italian"}, {"constructorId"=>"milano", "url"=>"http://en.wikipedia.org/wiki/Scuderia_Milano", "name"=>"Milano", "nationality"=>"Italian"}]}, {"position"=>"20", "positionText"=>"20", "points"=>"1", "wins"=>"0", "Driver"=>{"driverId"=>"chaboud", "url"=>"http://en.wikipedia.org/wiki/Eug%C3%A8ne_Chaboud", "givenName"=>"Eugène", "familyName"=>"Chaboud", "dateOfBirth"=>"1907-04-12", "nationality"=>"French"}, "Constructors"=>[{"constructorId"=>"lago", "url"=>"http://en.wikipedia.org/wiki/Talbot-Lago", "name"=>"Talbot-Lago", "nationality"=>"French"}]}, {"position"=>"21", "positionText"=>"21", "points"=>"1", "wins"=>"0", "Driver"=>{"driverId"=>"bettenhausen", "url"=>"http://en.wikipedia.org/wiki/Tony_Bettenhausen", "givenName"=>"Tony", "familyName"=>"Bettenhausen", "dateOfBirth"=>"1916-09-12", "nationality"=>"American"}, "Constructors"=>[{"constructorId"=>"deidt", "url"=>"http://en.wikipedia.org/wiki/Deidt", "name"=>"Deidt", "nationality"=>"American"}, {"constructorId"=>"kurtis_kraft", "url"=>"http://en.wikipedia.org/wiki/Kurtis_Kraft", "name"=>"Kurtis Kraft", "nationality"=>"American"}]}, {"position"=>"22", "positionText"=>"22", "points"=>"1", "wins"=>"0", "Driver"=>{"driverId"=>"chitwood", "url"=>"http://en.wikipedia.org/wiki/Joie_Chitwood", "givenName"=>"Joie", "familyName"=>"Chitwood", "dateOfBirth"=>"1912-04-14", "nationality"=>"American"}, "Constructors"=>[{"constructorId"=>"kurtis_kraft", "url"=>"http://en.wikipedia.org/wiki/Kurtis_Kraft", "name"=>"Kurtis Kraft", "nationality"=>"American"}]}, {"position"=>"23", "positionText"=>"23", "points"=>"0", "wins"=>"0", "Driver"=>{"driverId"=>"graffenried", "url"=>"http://en.wikipedia.org/wiki/Toulo_de_Graffenried", "givenName"=>"Toulo", "familyName"=>"de Graffenried", "dateOfBirth"=>"1914-05-18", "nationality"=>"Swiss"}, "Constructors"=>[{"constructorId"=>"maserati", "url"=>"http://en.wikipedia.org/wiki/Maserati", "name"=>"Maserati", "nationality"=>"Italian"}]}, {"position"=>"24", "positionText"=>"24", "points"=>"0", "wins"=>"0", "Driver"=>{"driverId"=>"gerard", "url"=>"http://en.wikipedia.org/wiki/Bob_Gerard", "givenName"=>"Bob", "familyName"=>"Gerard", "dateOfBirth"=>"1914-01-19", "nationality"=>"British"}, "Constructors"=>[{"constructorId"=>"era", "url"=>"http://en.wikipedia.org/wiki/English_Racing_Automobiles", "name"=>"ERA", "nationality"=>"British"}]}, {"position"=>"25", "positionText"=>"25", "points"=>"0", "wins"=>"0", "Driver"=>{"driverId"=>"villoresi", "url"=>"http://en.wikipedia.org/wiki/Luigi_Villoresi", "givenName"=>"Luigi", "familyName"=>"Villoresi", "dateOfBirth"=>"1909-05-16", "nationality"=>"Italian"}, "Constructors"=>[{"constructorId"=>"ferrari", "url"=>"http://en.wikipedia.org/wiki/Scuderia_Ferrari", "name"=>"Ferrari", "nationality"=>"Italian"}]}, {"position"=>"26", "positionText"=>"26", "points"=>"0", "wins"=>"0", "Driver"=>{"driverId"=>"pozzi", "url"=>"http://en.wikipedia.org/wiki/Charles_Pozzi", "givenName"=>"Charles", "familyName"=>"Pozzi", "dateOfBirth"=>"1909-08-27", "nationality"=>"French"}, "Constructors"=>[{"constructorId"=>"lago", "url"=>"http://en.wikipedia.org/wiki/Talbot-Lago", "name"=>"Talbot-Lago", "nationality"=>"French"}]}, {"position"=>"27", "positionText"=>"27", "points"=>"0", "wins"=>"0", "Driver"=>{"driverId"=>"wallard", "url"=>"http://en.wikipedia.org/wiki/Lee_Wallard", "givenName"=>"Lee", "familyName"=>"Wallard", "dateOfBirth"=>"1910-09-07", "nationality"=>"American"}, "Constructors"=>[{"constructorId"=>"moore", "url"=>"http://en.wikipedia.org/wiki/Moore_(constructor)", "name"=>"Moore", "nationality"=>"American"}]}, {"position"=>"28", "positionText"=>"28", "points"=>"0", "wins"=>"0", "Driver"=>{"driverId"=>"claes", "url"=>"http://en.wikipedia.org/wiki/Johnny_Claes", "givenName"=>"Johnny", "familyName"=>"Claes", "dateOfBirth"=>"1916-08-11", "nationality"=>"Belgian"}, "Constructors"=>[{"constructorId"=>"lago", "url"=>"http://en.wikipedia.org/wiki/Talbot-Lago", "name"=>"Talbot-Lago", "nationality"=>"French"}]}, {"position"=>"29", "positionText"=>"29", "points"=>"0", "wins"=>"0", "Driver"=>{"driverId"=>"levegh", "url"=>"http://en.wikipedia.org/wiki/Pierre_Levegh", "givenName"=>"Pierre", "familyName"=>"Levegh", "dateOfBirth"=>"1905-12-22", "nationality"=>"French"}, "Constructors"=>[{"constructorId"=>"lago", "url"=>"http://en.wikipedia.org/wiki/Talbot-Lago", "name"=>"Talbot-Lago", "nationality"=>"French"}]}, {"position"=>"30", "positionText"=>"30", "points"=>"0", "wins"=>"0", "Driver"=>{"driverId"=>"harrison", "url"=>"http://en.wikipedia.org/wiki/Cuth_Harrison", "givenName"=>"Cuth", "familyName"=>"Harrison", "dateOfBirth"=>"1906-07-06", "nationality"=>"British"}, "Constructors"=>[{"constructorId"=>"era", "url"=>"http://en.wikipedia.org/wiki/English_Racing_Automobiles", "name"=>"ERA", "nationality"=>"British"}]}]
    CONSTRUCTOR_STANDINGS_1992 = [{"position"=>"1", "positionText"=>"1", "points"=>"164", "wins"=>"10", "Constructor"=>{"constructorId"=>"williams", "url"=>"http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering", "name"=>"Williams", "nationality"=>"British"}}, {"position"=>"2", "positionText"=>"2", "points"=>"99", "wins"=>"5", "Constructor"=>{"constructorId"=>"mclaren", "url"=>"http://en.wikipedia.org/wiki/McLaren", "name"=>"McLaren", "nationality"=>"British"}}, {"position"=>"3", "positionText"=>"3", "points"=>"91", "wins"=>"1", "Constructor"=>{"constructorId"=>"benetton", "url"=>"http://en.wikipedia.org/wiki/Benetton_Formula", "name"=>"Benetton", "nationality"=>"Italian"}}, {"position"=>"4", "positionText"=>"4", "points"=>"21", "wins"=>"0", "Constructor"=>{"constructorId"=>"ferrari", "url"=>"http://en.wikipedia.org/wiki/Scuderia_Ferrari", "name"=>"Ferrari", "nationality"=>"Italian"}}, {"position"=>"5", "positionText"=>"5", "points"=>"13", "wins"=>"0", "Constructor"=>{"constructorId"=>"team_lotus", "url"=>"http://en.wikipedia.org/wiki/Team_Lotus", "name"=>"Team Lotus", "nationality"=>"British"}}, {"position"=>"6", "positionText"=>"6", "points"=>"8", "wins"=>"0", "Constructor"=>{"constructorId"=>"tyrrell", "url"=>"http://en.wikipedia.org/wiki/Tyrrell_Racing", "name"=>"Tyrrell", "nationality"=>"British"}}, {"position"=>"7", "positionText"=>"7", "points"=>"6", "wins"=>"0", "Constructor"=>{"constructorId"=>"footwork", "url"=>"http://en.wikipedia.org/wiki/Footwork_Arrows", "name"=>"Footwork", "nationality"=>"British"}}, {"position"=>"8", "positionText"=>"8", "points"=>"6", "wins"=>"0", "Constructor"=>{"constructorId"=>"ligier", "url"=>"http://en.wikipedia.org/wiki/Ligier", "name"=>"Ligier", "nationality"=>"French"}}, {"position"=>"9", "positionText"=>"9", "points"=>"3", "wins"=>"0", "Constructor"=>{"constructorId"=>"march", "url"=>"http://en.wikipedia.org/wiki/March_Engineering", "name"=>"March", "nationality"=>"British"}}, {"position"=>"10", "positionText"=>"10", "points"=>"2", "wins"=>"0", "Constructor"=>{"constructorId"=>"dallara", "url"=>"http://en.wikipedia.org/wiki/Dallara", "name"=>"Dallara", "nationality"=>"Italian"}}, {"position"=>"11", "positionText"=>"11", "points"=>"1", "wins"=>"0", "Constructor"=>{"constructorId"=>"jordan", "url"=>"http://en.wikipedia.org/wiki/Jordan_Grand_Prix", "name"=>"Jordan", "nationality"=>"Irish"}}, {"position"=>"12", "positionText"=>"12", "points"=>"1", "wins"=>"0", "Constructor"=>{"constructorId"=>"minardi", "url"=>"http://en.wikipedia.org/wiki/Minardi", "name"=>"Minardi", "nationality"=>"Italian"}}, {"position"=>"13", "positionText"=>"13", "points"=>"1", "wins"=>"0", "Constructor"=>{"constructorId"=>"larrousse", "url"=>"http://en.wikipedia.org/wiki/Larrousse", "name"=>"Larrousse", "nationality"=>"French"}}, {"position"=>"14", "positionText"=>"14", "points"=>"0", "wins"=>"0", "Constructor"=>{"constructorId"=>"fondmetal", "url"=>"http://en.wikipedia.org/wiki/Fondmetal", "name"=>"Fondmetal", "nationality"=>"Italian"}}, {"position"=>"15", "positionText"=>"15", "points"=>"0", "wins"=>"0", "Constructor"=>{"constructorId"=>"brabham", "url"=>"http://en.wikipedia.org/wiki/Brabham", "name"=>"Brabham", "nationality"=>"British"}}]


  end


  


end